try{
    consol.log('hello there')
}
catch(error)
{
    console.log(error)
}
finally
{
console.log('from final block');
}